### ISSUE TITLE
Add Code of Conduct Page

### ISSUE THREAD

**Issue by gilcreque** [SpaceCoastTechClub/www-gatsby#1]
Take HTML from previous [Code of Conduct page](https://github.com/SpaceCoastTechClub/www/blob/master/src/app/code-of-conduct/code-of-conduct.component.html), convert to Markdown, and then add it as a page in Gatsby. The route should be `/coc`.

**Comment by rlynn523** [comment]
I can take this if it's still available

**Comment by gilcreque** [comment]
@rlynn523 it's all you.
